export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_CHANGE = "AUTH_CHANGE";
export const AUTH_CHANGE_SUCCESS = "AUTH_CHANGE_SUCCESS";
export const AUTH_CHANGE_FAILURE = "AUTH_CHANGE_FAILURE";

export const START_CHANGE = "START_CHANGE";
export const START_CHANGE_SUCCESS = "START_CHANGE_SUCCESS";
export const START_CHANGE_FAILURE = "START_CHANGE_FAILURE";

export const RECIPE_LIST = "RECIPE_LIST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAILURE = "RECIPE_LIST_FAILURE";

export const EATEN_LIST = "EATEN_LIST";
export const EATEN_LIST_SUCCESS = "EATEN_LIST_SUCCESS";
export const EATEN_LIST_FAILURE = "EATEN_LIST_FAILURE";

export const RECIPE_SCRAP = "RECIPE_SCRAP";
export const RECIPE_SCRAP_SUCCESS = "RECIPE_SCRAP_SUCCESS";
export const RECIPE_SCRAP_FAILURE = "RECIPE_SCRAP_FAILURE";

export const RECIPE_EAT = "RECIPE_EAT";
export const RECIPE_EAT_SUCCESS = "RECIPE_EAT_SUCCESS";
export const RECIPE_EAT_FAILURE = "RECIPE_EAT_FAILURE";

export const RECIPE_SEARCH = "RECIPE_SEARCH";
export const RECIPE_SEARCH_SUCCESS = "RECIPE_SEARCH_SUCCESS";
export const RECIPE_SEARCH_FAILURE = "RECIPE_SEARCH_FAILURE";

export const SCRAP_LOAD = "SCRAP_LOAD";
export const SCRAP_LOAD_SUCCESS = "SCRAP_LOAD_SUCCESS";
export const SCRAP_LOAD_FAILURE = "SCRAP_LOAD_FAILURE";

export const INFO_LOAD = "INFO_LOAD";
export const INFO_LOAD_SUCCESS = "INFO_LOAD_SUCCESS";
export const INFO_LOAD_FAILURE = "INFO_LOAD_FAILURE";

export const INGREDIENT_SEARCH = "INGREDIENT_SEARCH";
export const INGREDIENT_SEARCH_SUCCESS = "INGREDIENT_SEARCH_SUCCESS";
export const INGREDIENT_SEARCH_FAILURE = "INGREDIENT_SEARCH_FAILURE";

export const INGREDIENT_EAT = "INGREDIENT_EAT";
export const INGREDIENT_EAT_SUCCESS = "INGREDIENT_EAT_SUCCESS";
export const INGREDIENT_EAT_FAILURE = "INGREDIENT_EAT_FAILURE";

export const SCRAP_DELETE = "SCRAP_DELETE";
export const SCRAP_DELETE_SUCCESS = "SCRAP_DELETE_SUCCESS";
export const SCRAP_DELETE_FAILURE = "SCRAP_DELETE_FAILURE";

export const EAT_DELETE = "EAT_DELETE";
export const EAT_DELETE_SUCCESS = "EAT_DELETE_SUCCESS";
export const EAT_DELETE_FAILURE = "EAT_DELETE_FAILURE";

export const GET_SETTING = "GET_SETTING";
export const GET_SETTING_SUCCESS = "GET_SETTING_SUCCESS";
export const GET_SETTING_FAILURE = "GET_SETTING_FAILURE";

export const VEGEKEY_LIST = "VEGEKEY_LIST";
export const VEGEKEY_LIST_SUCCESS = "VEGEKEY_LIST_SUCCESS";
export const VEGEKEY_LIST_FAILURE = "VEGEKEY_LIST_FAILURE";