export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAILURE = "AUTH_REGISTER_FAILURE";

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";

export const AUTH_GET_STATUS = "AUTH_GET_STATUS";
export const AUTH_GET_STATUS_SUCCESS = "AUTH_GET_STATUS_SUCCESS";
export const AUTH_GET_STATUS_FAILURE = "AUTH_GET_STATUS_FAILURE";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const RECIPE_LIST = "RECIPE_LIST";
export const RECIPE_LIST_SUCCESS = "RECIPE_LIST_SUCCESS";
export const RECIPE_LIST_FAILURE = "RECIPE_LIST_FAILURE";


export const EATEN_LIST = "EATEN_LIST";
export const EATEN_LIST_SUCCESS = "EATEN_LIST_SUCCESS";
export const EATEN_LIST_FAILURE = "EATEN_LIST_FAILURE";

export const RECIPE_SCRAP = "RECIPE_SCRAP";
export const RECIPE_SCRAP_SUCCESS = "RECIPE_SCRAO_SUCCESS";
export const RECIPE_SCRAP_FAILURE = "RECIPE_SCRAP_FAILURE";

export const RECIPE_EAT = "RECIPE_EAT";
export const RECIPE_EAT_SUCCESS = "RECIPE_EAT_SUCCESS";
export const RECIPE_EAT_FAILURE = "RECIPE_EAT_FAILURE";

export const RECIPE_SEARCH = "RECIPE_SEARCH";
export const RECIPE_SEARCH_SUCCESS = "RECIPE_SEARCH_SUCCESS";
export const RECIPE_SEARCH_FAILURE = "RECIPE_SEARCH_FAILURE";

export const RECIPE_FILTER = "RECIPE_FILTER";
export const RECIPE_FILTER_SUCCESS = "RECIPE_FILTER_SUCCESS";
export const RECIPE_FILTER_FAILURE = "RECIPE_FILTER_FAILURE";
